import { useState } from 'react'
import { issueUrl, type Plugin } from '../lib/catalog'

const checklist = { behavior: 'Behavior matches the stated purpose', manifest: 'Manifest is correct', entrypoints: 'Entry points are valid', malware: 'No obvious malicious behavior', capabilities: 'Capabilities are accurately reported', ownership: 'Repository belongs to the expected project', obfuscation: 'No suspicious obfuscated code', downloads: 'External downloads are explained', credentials: 'Credential access is explained', shell: 'No unrelated shell commands', destructive: 'No obvious destructive behavior', description: 'Description matches actual behavior' }
const reasons = ['Malware', 'Suspicious behavior', 'Broken plugin', 'Misleading description', 'Impersonation', 'Spam', 'Copyright issue', 'Security issue', 'Other']

export function ReviewForm({ plugin }: { plugin: Plugin }) {
  const canApprove = plugin.scan?.validation === 'passed' && Boolean(plugin.scanDigest)
  const [action, setAction] = useState(canApprove ? 'approve' : 'changes')
  return <><details id="report" className="digest-details"><summary>Report this plugin</summary><form className="submission-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); window.location.assign(issueUrl('report', `Report: ${plugin.name}`, { package: plugin.package, reason: data.get('reason'), notes: data.get('notes') })) }}><label htmlFor="report-reason">Reason</label><select id="report-reason" name="reason" required defaultValue=""><option value="" disabled>Choose a reason</option>{reasons.map(reason => <option key={reason}>{reason}</option>)}</select><label htmlFor="report-notes">Explanation (optional, public)</label><textarea id="report-notes" name="notes" maxLength={4000} /><button className="button" type="submit">Continue on GitHub ↗</button><p>A report requests a rescan and moderation. It does not remove a plugin automatically.</p></form></details>
    <section id="review-actions" className="review-panel" aria-labelledby="review-heading"><p className="eyebrow">For authorized reviewers</p><h2 id="review-heading">Review this plugin</h2><p>Inspect the source and scan above, choose a decision, then submit the prepared issue on GitHub. Only configured reviewer accounts can record a decision.</p><form className="submission-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); window.location.assign(issueUrl('review', `${action}: ${plugin.name}`, { package: plugin.package, commit: plugin.commit, scanDigest: plugin.scanDigest, action, checklist: data.getAll('checklist'), notes: data.get('notes'), recommendation: data.get('recommendation') })) }}><p>Reviewing commit <code>{plugin.commit}</code>. GitHub identity is checked by the registry before any decision is recorded.</p><label htmlFor="review-action">Decision</label><select id="review-action" value={action} onChange={event => setAction(event.target.value)}><option value="approve" disabled={!canApprove}>Approve</option><option value="reject">Reject</option><option value="changes">Request changes</option><option value="flag">Flag for review</option><option value="revoke">Revoke</option></select>
      {!canApprove && <p className="notice">Approval is unavailable until this commit has a passing scan. Request changes with the fixes needed, or return after the next scan.</p>}
      {action === 'revoke' && <label className="review-check"><input type="checkbox" required key={action} />I understand this withdraws trust from the displayed commit and records a public reason.</label>}
      {action === 'approve' && <fieldset><legend>Code review checklist</legend>{Object.entries(checklist).map(([key, label]) => <label className="review-check" key={key}><input type="checkbox" name="checklist" value={key} required />{label}</label>)}</fieldset>}<p>All notes are public. Do not include credentials or private vulnerability details.</p><label htmlFor="review-notes">Review notes / reason</label><textarea id="review-notes" name="notes" required maxLength={4000} placeholder="Describe what you checked, what needs fixing, or why trust is being withdrawn." /><label htmlFor="recommendation">Advisory recommendation (optional)</label><textarea id="recommendation" name="recommendation" maxLength={2000} /><button className="button" type="submit">Continue on GitHub ↗</button><p>Next: sign in with your reviewer account and submit the GitHub issue. Opening the draft does not record your decision.</p></form></section></>
}
