import { useState } from 'react'
import { issueUrl, type Plugin } from '../lib/catalog'

const checklist = { behavior: 'Behavior matches the stated purpose', manifest: 'Manifest is correct', entrypoints: 'Entry points are valid', malware: 'No obvious malicious behavior', capabilities: 'Capabilities are accurately reported', ownership: 'Repository belongs to the expected project', obfuscation: 'No suspicious obfuscated code', downloads: 'External downloads are explained', credentials: 'Credential access is explained', shell: 'No unrelated shell commands', destructive: 'No obvious destructive behavior', description: 'Description matches actual behavior' }
const reasons = ['Malware', 'Suspicious behavior', 'Broken plugin', 'Misleading description', 'Impersonation', 'Spam', 'Copyright issue', 'Security issue', 'Other']

export function ReviewForm({ plugin }: { plugin: Plugin }) {
  const [action, setAction] = useState('approve')
  return <><details className="digest-details"><summary>Report this plugin</summary><form className="submission-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); window.location.assign(issueUrl('report', `Report: ${plugin.name}`, { package: plugin.package, reason: data.get('reason'), notes: data.get('notes') })) }}><label htmlFor="report-reason">Reason</label><select id="report-reason" name="reason">{reasons.map(reason => <option key={reason}>{reason}</option>)}</select><label htmlFor="report-notes">Explanation (optional, public)</label><textarea id="report-notes" name="notes" maxLength={4000} /><button className="button" type="submit">Continue on GitHub ↗</button><p>A report requests a rescan and moderation. It does not remove a plugin automatically.</p></form></details>
    <details className="digest-details"><summary>Reviewer actions</summary><form className="submission-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); window.location.assign(issueUrl('review', `${action}: ${plugin.name}`, { package: plugin.package, commit: plugin.commit, scanDigest: plugin.scanDigest, action, checklist: data.getAll('checklist'), notes: data.get('notes'), recommendation: data.get('recommendation') })) }}><p>Reviewing commit <code>{plugin.commit}</code>. GitHub identity is checked by the registry before any decision is recorded.</p><label htmlFor="review-action">Decision</label><select id="review-action" value={action} onChange={event => setAction(event.target.value)}><option value="approve">Approve</option><option value="reject">Reject</option><option value="changes">Request changes</option><option value="flag">Flag for review</option><option value="revoke">Revoke</option></select>
      {action === 'approve' && <fieldset><legend>Code review checklist</legend>{Object.entries(checklist).map(([key, label]) => <label className="review-check" key={key}><input type="checkbox" name="checklist" value={key} required />{label}</label>)}</fieldset>}<label htmlFor="review-notes">Review notes / reason</label><textarea id="review-notes" name="notes" required maxLength={4000} /><label htmlFor="recommendation">Advisory recommendation (optional)</label><textarea id="recommendation" name="recommendation" maxLength={2000} /><button className="button" type="submit">Continue on GitHub ↗</button></form></details></>
}
